export const unidadPresupuestalPorUnidadResponsable = {
  'Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado': [
      '01. Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado',
      '02. Dirección General de Relaciones Públicas',
      '03. Secretaría Técnica del Despacho del Gobernador',
      '04. Dirección General de Estudios Legislativos',
      '05. Coordinación de Agenda y Audiencia Pública',
      '06. Dirección General de Giras',
      '07. Dirección General de Atención al Pueblo',
      '08. Dirección General de Desarrollo Institucional',
      '09. Coordinación de Seguimiento',
      '10. Coordinación de Gestión y Vinculación de Proyectos Especiales',
      '11. Coordinación de Operación Institucional'
  ],
  'Secretaría de Gobierno': [
      '01. Secretaría de Gobierno',
      '02. Subsecretaría de Gobernación',
      '03. Dirección General de Investigaciones Políticas y Sociales',
      '04. Dirección General de Asuntos Agrarios',
      '05. Subsecretaría de Gobierno en la Huasteca Hidalguense',
      '06. Subsecretaría de Gobierno en el Valle del Mezquital',
      '07. Subsecretaría de Desarrollo Político',
      '08. Dirección General de Desarrollo Político',
      '09. Coordinación General Jurídica',
      '10. Dirección General Jurídica',
      '11. Subsecretaría de Protección Civil y Gestión de Riesgos',
      '12. Dirección General de Protección Civil y Gestión de Riesgos',
      '13. Central Estatal de Información, Investigación e Inteligencia',
      '14. Consejo Estatal de Población',
      '15. Instituto de la Defensoría Pública del Estado de Hidalgo',
      '16. Dirección General del Mando Coordinado',
      '17. Dirección General del Instituto de la Función Registral',
      '18. Secretaría Ejecutiva del Sistema Estatal de Protección Integral de los derechos de Niñas, Niños y Adolescentes del Estado de Hidalgo',
      '19. Secretariado Ejecutivo del Consejo Estatal de Seguridad Pública',
      '20. Dirección General de Asuntos Religiosos',
      '21. Dirección General de Unidades de Servicios Estatales',
      '22. Coordinación General de Comunicación Gubernamental',
      '23. Dirección General de Derechos Humanos',
      '24. Dirección General del Registro del Estado Familiar',
      '25. Dirección General de Archivo General de Notarías',
      '26. Comisión de Búsqueda de Personas del Estado de Hidalgo',
      '27. Dirección General Editorial'
  ],
  'Secretaría de Hacienda': [
      '01. Secretaría de Hacienda',
      '02. Coordinación de Planeación Financiera',
      '03. Procuraduría Fiscal del Estado de Hidalgo',
      '04. Unidad Técnica de Evaluación del Desempeño',
      '05. Subsecretaría de Egresos',
      '06. Dirección General de Contabilidad Gubernamental',
      '07. Dirección General de Tesorería',
      '08. Dirección General de Normatividad Contable Presupuestal',
      '09. Dirección General de Atención y Seguimiento a Auditorías',
      '10. Subsecretaría de Ingresos',
      '11. Dirección General de Auditoría Fiscal',
      '12. Dirección General de Recaudación',
      '13. Coordinación de Tecnologías de la Información',
      '14. Dirección General de Atención al Contribuyente',
      '15. Coordinación del Gasto de Inversión',
      '16. Subsecretaría de Programación y Presupuesto del Gasto de Inversión',
      '17. Dirección General de Programación',
      '18. Dirección General de Validación Técnica de Estudios y Proyectos',
      '19. Dirección General de Monitoreo y Seguimiento al Recurso Público',
      '20. Coordinación de Representación Institucional',
      '21. Unidad de Inteligencia Patrimonial y Económica',
      '22. Dirección General de Administración'
  ],
  'Secretaría de Bienestar e Inclusión Social': [
      '01. Secretaría de Bienestar e Inclusión Social',
      '02. Dirección General de Fomento Artesanal',
      '03. Subsecretaría de Inclusión y Desarrollo',
      '04. Dirección General de Operación y Logística de Programas',
      '05. Dirección General de Atención al Migrante',
      '06. Dirección General de Asistencia, Atención y Protección',
      '07. Dirección General de Prospectiva, Planeación y Evaluación de los Programas Sociales',
      '08. Subsecretaría de Participación Social y Fomento Artesanal',
      '09. Dirección General de Inclusión para las Personas con Discapacidad',
      '10. Subsecretaría de Desarrollo Social y Humano'
  ],
  'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': [
      '01. Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible',
      '02. Subsecretaría de Infraestructura Pública',
      '03. Dirección General de Obras Públicas e Infraestructura',
      '04. Dirección General de Infraestructura y Vías de Comunicación',
      '05. Dirección General de Conservación de Carreteras Estatales',
      '06. Subsecretaría de Desarrollo Urbano Sostenible',
      '07. Dirección General de Imagen y Desarrollo Urbano Sostenible',
      '08. Subsecretaría de Gestión de Proyectos',
      '09. Dirección General de Estudios y Proyectos',
      '10. Dirección General de Supervisión Estratégica y Evaluación',
      '11. Dirección General de Tecnologías de Información y Mejora Continua',
      '12. Dirección General de Asuntos Jurídicos',
      '13. Dirección General de Administración',
      '14. Dirección General de Atención y Vinculación Institucional'
  ],
  'Secretaría de Medio Ambiente y Recursos Naturales': [
      '01. Secretaría de Medio Ambiente y Recursos Naturales',
      '02. Subsecretaría de Política Ambiental',
      '03. Dirección General de Ordenamiento Ecológico Territorial',
      '04. Dirección General de Recursos Naturales',
      '05. Dirección General de Gestión de Calidad del Aire',
      '06. Consejo de Administración del Parque Nacional "El Chico"',
      '07. Procuraduría Estatal de Protección al Ambiente',
      '08. Dirección General de Normatividad Ambiental',
      '09. Dirección General de Cuencas y Planeación Hídrica',
      '10. Subsecretaría de Sustentabilidad y Cambio Climático',
      '11. Dirección General de Cambio Climático'
  ],
  'Secretaría de Desarrollo Económico': [
      '01. Secretaría de Desarrollo Económico',
      '02. Subsecretaría de Inversiones y Economía Sectorial',
      '03. Dirección General de Economía Sectorial',
      '04. Dirección General de Inversiones',
      '05. Subsecretaría de Fomento Económico',
      '06. Dirección General de Fomento al Empleo',
      '07. Dirección General de Fomento Económico'
  ],
  'Secretaría de Agricultura y Desarrollo Rural': [
      '01. Secretaría de Agricultura y Desarrollo Rural',
      '02. Subsecretaría de Desarrollo Agropecuario',
      '03. Dirección General de Agricultura',
      '04. Dirección General de Ganadería',
      '05. Dirección General de Desarrollo Rural',
      '06. Dirección General de Silvicultura, Fruticultura, Acuacultura y del Maguey',
      '07. Dirección General de Infraestructura y Maquinaria',
      '08. Subsecretaría de Agronegocios',
      '09. Dirección General de Comercialización y Mercadotecnia',
      '10. Subsecretaría de Planeación y Evaluación Sectorial',
      '11. Dirección General de Evaluación y Programas Estratégicos',
      '12. Dirección General de Fomento al Crédito',
      '13. Dirección General de Fomento Lechero',
      '14. Dirección General de Desarrollo de la Cafeticultura'
  ],
  'Secretaría de Turismo': [
      '01. Secretaría de Turismo',
      '02. Dirección General de Productos Turísticos y Pueblos Mágicos',
      '03. Dirección General de Promoción y Mercadotecnia',
      '04. Dirección General de Formación y Competitividad Turística',
      '05. Dirección General de Programas Turísticos y Alianzas Estratégicas',
      '06. Dirección de Planeación y Evaluación',
      '07. Subsecretaría de Turismo',
      '08. Dirección de Innovación, Desarrollo de Productos Turísticos e Infraestructura'
  ],
  'Secretaría de Contraloría': [
      '01. Secretaría de Contraloría',
      '02. Dirección General de Órganos de Control y Vigilancia',
      '03. Dirección General de Inspección y Vigilancia de Obras y Acciones',
      '04. Dirección General de Normatividad',
      '05. Dirección General de Responsabilidades Administrativas',
      '06. Dirección General de Vinculación',
      '07. Dirección General de Auditoría Gubernamental'
  ],
  'Secretaría de Educación Pública': [
      '01. Secretaría de Educación Pública',
      '02. Subsecretaría de Administración y Finanzas',
      '03. Subsecretaría de Educación Básica',
      '04. Subsecretaría de Educación Media Superior y Superior',
      '05. Subsecretaría de Planeación y Evaluación',
      '06. Centro Estatal de Lenguas y Culturas Indígenas'
  ],
  'Secretaría de Salud': [
      '01. Secretaría de Salud',
      '02. Subsecretaría de Salud Pública',
      '03. Subsecretaría de Servicios de Salud',
      '04. Subsecretaría de Administración, Finanzas y Planeación',
      '05. Comisión de Arbitraje Médico del Estado de Hidalgo',
      '06. Comisión para la Protección contra Riesgos Sanitarios del Estado de Hidalgo',
      '07. Dirección General de Proyectos Estratégicos de Salud',
      '08. Centro Estatal de Trasplantes de Órganos, Tejidos y Células de Humanos para el Estado de Hidalgo'
  ],
  'Secretaría de Seguridad Pública': [
      '01. Secretaría de Seguridad Pública',
      '02. Subsecretaría de Prevención y Reinserción Social',
      '03. Dirección General de Prevención y Reinserción Social',
      '04. Subsecretaría de C5i',
      '05. Dirección General de Servicios Aéreos',
      '06. Subsecretaría de Prevención y Coordinación Institucional',
      '07. Dirección General del Centro Estatal de Prevención Social de la Violencia y la Delincuencia',
      '08. Dirección General de Asuntos Jurídicos y Derechos Humanos',
      '09. Subsecretaría de Operación Policial',
      '10. Instituto de Formación Profesional',
      '11. Centro Estatal de Evaluación y Control de Confianza',
      '12. Unidad de Medidas Cautelares',
      '13. Dirección General de Ayudantía Personal',
      '14. Dirección General de Supervisión e Inspección Interna'
  ],
  'Secretaría del Trabajo y Previsión Social': [
      '01. Secretaría del Trabajo y Previsión Social',
      '02. Dirección General del Trabajo y Previsión Social',
      '03. Dirección General del Servicio Nacional de Empleo',
      '04. Junta Local de Conciliación y Arbitraje',
      '05. Tribunal de Arbitraje',
      '06. Procuraduría Estatal de la Defensa del Trabajo'
  ],
  'Secretaría de Movilidad y Transporte': [
      '01. Secretaría de Movilidad y Transporte',
      '02. Subsecretaría de Movilidad y Transporte',
      '03. Dirección General de Normatividad',
      '04. Dirección General de Movilidad Sustentable'
  ],
  'Secretaría de Cultura': [
      '01. Secretaría de Cultura',
      '02. Dirección General de Diversidad Cultural y Fomento a la Lectura, Escritura y Oralidad',
      '03. Dirección General de Cultura Digital',
      '04. Dirección General de Vinculación, Programación y Difusión Cultural',
      '05. Subsecretaría de Desarrollo Cultural',
      '06. Dirección General de Cultura Originaria, Popular y Urbana',
      '07. Dirección General de Patrimonio Cultural'
  ],
  'Unidad de Planeación y Prospectiva': [
      '01. Unidad de Planeación y Prospectiva',
      '02. Coordinación General de Normatividad y Entidades Paraestatales',
      '03. Dirección General de Consulta y Normatividad',
      '04. Dirección General de Control y Seguimiento a Entidades Paraestatales',
      '05. Coordinación General de Planeación y Proyectos',
      '06. Dirección General de Análisis Geográfico y Mejora a las Políticas Públicas',
      '07. Dirección General de Planeación y Participación Ciudadana',
      '08. Dirección General de Desarrollo Regional y Metropolitano',
      '09. Coordinación General de Evaluación y Políticas Públicas',
      '10. Dirección General de Evaluación',
      '11. Dirección General de Monitoreo',
      '12. Dirección General de Percepción e Impacto Ciudadano',
      '13. Dirección General de Proyectos, Estudios y Prospectiva',
      '14. Comisión Estatal de Mejora Regulatoria'
  ],
  'Oficialía Mayor': [
      '01. Oficialía Mayor',
      '02. Dirección General de Compras Públicas',
      '03. Dirección General de Patrimonio Inmobiliario',
      '04. Dirección General de Recursos Materiales y Servicios',
      '05. Dirección General de Recursos Humanos',
      '06. Archivo General del Estado de Hidalgo',
      '07. Dirección General de Innovación Gubernamental',
      '08. Coordinación General de la Oficialía Mayor'
  ],
  'Procuraduría General de Justicia': [
      '01. Procuraduría General de Justicia',
      '02. Subprocuraduría Oriente',
      '03. Dirección General del Sistema Mixto',
      '04. Fiscalía Especializada en Delitos Electorales',
      '05. Subprocuraduría de Delitos de Género, Desaparición de Personas e Impacto Social',
      '06. Visitaduría General',
      '07. Unidad Especializada en el Combate al Secuestro',
      '08. Oficialía Mayor',
      '09. Subprocuraduría Poniente',
      '10. Fiscalía Especializada en Delitos de Corrupción',
      '11. Subprocuraduría Jurídica y de Derechos Humanos',
      '12. Unidad de Recuperación de Vehículos',
      '13. Agencia de investigación Criminal',
      '14. Centro de Justicia Restaurativa',
      '15. Órgano Interno de Control'
  ],
  'Organismos Descentralizados': [
      '01. Radio y Televisión de Hidalgo',
      '02. Instituto Hidalguense para el Desarrollo Municipal',
      '03. Instituto Catastral del Estado de Hidalgo',
      '04. Instituto Hidalguense de las Mujeres',
      '05. Instituto Hidalguense de la Juventud',
      '06. Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo',
      '07. Centro Estatal de Maquinaria para el Desarrollo',
      '08. Comisión Estatal de Vivienda',
      '09. Comisión Estatal del Agua y Alcantarillado',
      '10. Comisión de Agua y Alcantarillado de Sistemas Intermunicipales',
      '11. Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital',
      '12. Instituto de Vivienda, Desarrollo Urbano y Asentamientos Humanos',
      '13. Sistema de Autopistas, Servicios Conexos y Auxiliares del Estado de Hidalgo',
      '14. Corporación Internacional Hidalgo',
      '15. Corporación de Fomento de Infraestructura Industrial',
      '16. Operadora de Eventos del Estado de Hidalgo',
      '17. Instituto Hidalguense de Competitividad Empresarial',
      '18. Agencia de Desarrollo Valle de Plata',
      '19. Consejo Estatal para la Cultura y las Artes de Hidalgo',
      '20. Instituto Hidalguense de Educación',
      '21. Instituto Hidalguense de Educación para Adultos',
      '22. Universidad Politécnica de Tulancingo',
      '23. Universidad Politécnica de Pachuca',
      '24. Universidad Politécnica de Francisco I. Madero',
      '25. Universidad Politécnica de Huejutla',
      '26. Universidad Politécnica Metropolitana de Hidalgo',
      '27. Universidad Tecnológica de Tula–Tepeji',
      '28. Universidad Tecnológica de Tulancingo',
      '29. Universidad Tecnológica de la Huasteca Hidalguense',
      '30. Universidad Tecnológica del Valle del Mezquital',
      '31. Universidad Tecnológica de la Sierra Hidalguense',
      '32. Universidad Tecnológica de la Zona Metropolitana del Valle de México',
      '33. Instituto Tecnológico Superior de Huichapan',
      '34. Instituto Tecnológico Superior del Occidente del Estado de Hidalgo',
      '35. Instituto Tecnológico Superior del Oriente del Estado de Hidalgo',
      '36. Universidad Intercultural del Estado de Hidalgo',
      '37. Colegio de Bachilleres del Estado de Hidalgo',
      '38. Bachillerato del Estado de Hidalgo',
      '39. Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo',
      '40. Colegio de Educación Profesional Técnica del Estado de Hidalgo',
      '41. El Colegio del Estado de Hidalgo',
      '42. Escuela de Música del Estado de Hidalgo',
      '43. Instituto Hidalguense de Financiamiento a la Educación Superior',
      '44. Instituto Hidalguense del Deporte',
      '45. Instituto Hidalguense de la Infraestructura Física Educativa',
      '46. Servicios de Salud de Hidalgo',
      '47. Instituto de Capacitación para el Trabajo del Estado de Hidalgo',
      '48. Policía Industrial Bancaria del Estado de Hidalgo',
      '49. Centro de Justicia para Mujeres del Estado de Hidalgo',
      '50. Sistema de Transporte Convencional de Hidalgo',
      '51. Sistema Integrado de Transporte Masivo de Hidalgo',
      '52. Universidad Tecnológica Minera de Zimapán',
      '53. Universidad Tecnológica de Mineral de la Reforma',
      '54. Universidad Politécnica de la Energía',
      '55. Ciudad de las Mujeres',
      '56. Agencia Estatal de Energía de Hidalgo',
      '57. Centro de Conciliación Laboral del Estado de Hidalgo',
      '58. Comisión Estatal de Biodiversidad de Hidalgo',
      '59. Universidad Digital del Estado de Hidalgo',
      '60. Comisión Ejecutiva de Atención a Víctimas del Estado de Hidalgo',
      '61. Instituto Hidalguense para Devolver al Pueblo lo Robado'
  ],
  'Organismos Descentralizados no Sectorizados': [
      '01. Secretaría Técnica del Sistema Estatal Anticorrupción de Hidalgo',
      '02. Sistema para el Desarrollo Integral de la Familia del Estado de Hidalgo',
      '03. Comisión Estatal para el Desarrollo Sostenible de los Pueblos Indígenas (CEDSPI)',
      '04. Consejo de Ciencia, Tecnología e Innovación de Hidalgo (CITNOVA)',
      '05. Universidad Autónoma del Estado de Hidalgo',
      '06. Museo Interactivo para la Niñez y la Juventud Hidalguense “El Rehilete”',
      '07. Consejo Ejecutivo del Complejo Científico y Tecnológico Sincrotrón en el Estado de Hidalgo',
      '08. Coordinación General del Distrito de Educación, Salud, Ciencia, Tecnología e Innovación'
  ]
};

export const acuerdosPorObjetivo = {
  '1. Acuerdo para un Gobierno Cercano, Justo y Honesto': [
      '1.1 Un gobierno itinerante y cercano al pueblo desde el primer día',
      '1.2 Con el pueblo todo, sin el pueblo, nada',
      '1.3 Transformación de la administración pública del estado de Hidalgo, con base en la honestidad, transparencia y eficiencia',
      '1.4 Transparencia y rendición de cuentas, principios fundamentales de nuestra administración',
      '1.5 Fortalecer el Sistema Estatal Anticorrupción',
      '1.6 Finanzas Públicas',
      '1.7 Impulso a la Gobernanza y Desarrollo Político',
      '1.8 Recuperación de la Paz en Hidalgo con una nueva política estatal de seguridad ciudadana',
      '1.9 Fortalecimiento de la Procuración de Justicia',
      '1.10 Objetivos Transversales para un Gobierno Cercano, Justo y Honesto'
  ],
  '2. Acuerdo para el Bienestar del Pueblo': [
      '2.1 Servicios de salud',
      '2.2 Desarrollo de la nueva política del bienestar con la participación de todas y todos',
      '2.3 Agenda del Bienestar "Primero los Pobres"',
      '2.4 Garantizar una atención integral para las personas con discapacidad',
      '2.5 Garantizar el bienestar de las personas mayores',
      '2.6 El poder de las juventudes a través de su voz',
      '2.7 Atención a personas migrantes',
      '2.8 Garantizar los derechos de los pueblos y comunidades indígenas',
      '2.9 Desarrollo pleno e integral de las mujeres',
      '2.10 Fomentar la práctica del deporte',
      '2.11 Bienestar de las niñas, niños y adolescentes',
      '2.12 Objetivos Transversales para el Bienestar del Pueblo'
  ],
  '3. Acuerdo para el Desarrollo Económico': [
      '3.1 Una nueva política para el crecimiento y desarrollo económico',
      '3.2 Trabajo y previsión social',
      '3.3 Programa de Transformación del Sector Agropecuario',
      '3.4 Hidalgo potencia turística',
      '3.5 Desarrollo integral de la política cultural',
      '3.6 Educación para el futuro de Hidalgo',
      '3.7 Objetivos Transversales para el Desarrollo Económico'
  ],
  '4. Acuerdo para el Desarrollo Sostenible e Infraestructura Transformadora': [
      '4.1 Infraestructura para el desarrollo social y sostenible',
      '4.2 Planeación territorial y urbana',
      '4.3 Movilidad accesible, sostenible e incluyente',
      '4.4 Cuidado del medio ambiente',
      '4.5 Objetivos Transversales por el Desarrollo Sostenible e Infraestructura Transformadora'
  ]
};

export const dependencias = [
    'Secretaría del Despacho del Gobernador', 'Oficialía Mayor', 'Unidad de Planeación y Prospectiva',
    'Secretaría de Gobierno', 'Secretaría de Hacienda', 'Secretaría de Bienestar e Inclusión Social',
    'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible', 'Secretaría de Desarrollo Económico',
    'Secretaría de Medio Ambiente y Recursos Naturales', 'Secretaría de Agricultura y Desarrollo Rural',
    'Secretaría de Turismo', 'Secretaría de Contraloría', 'Secretaría de Educación Pública',
    'Secretaría de Salud', 'Secretaría de Seguridad Pública', 'Secretaría del Trabajo y Previsión Social',
    'Secretaría de Movilidad y Transporte', 'Secretaría de Cultura', 'Procuraduría de General de Justicia'
];

export const organismos = [
    'Centro de Justicia para Mujeres del Estado de Hidalgo', 'Ciudad de las Mujeres', 'Instituto Hidalguense de las Mujeres',
    'Instituto Hidalguense para el Desarrollo Municipal', 'Instituto Catastral del Estado de Hidalgo',
    'Instituto para Devolver al Pueblo lo Robado', 'Centro Estatal de Maquinaria para el Desarrollo',
    'Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital', 'Comisión de Agua y Alcantarillado de Sistemas Intermunicipales',
    'Comisión Estatal del Agua y Alcantarillado', 'Comisión Estatal de Vivienda', 'Policía Industrial Bancaria del Estado de Hidalgo',
    'Consejo Estatal para la Cultura y las Artes de Hidalgo', 'Escuela de Música del Estado de Hidalgo',
    'Servicios de Salud de Hidalgo', 'Agencia de Desarrollo Valle de Plata', 'Agencia Estatal de Energía',
    'Corporación de Fomento de Infraestructura Industrial', 'Corporación Internacional Hidalgo',
    'Instituto Hidalguense de Competitividad Empresarial', 'Comisión Estatal de Biodiversidad de Hidalgo',
    'Centro de Conciliación Laboral del Estado de Hidalgo', 'Instituto de Capacitación para el Trabajo del Estado de Hidalgo',
    'Operadora de Eventos del Estado de Hidalgo', 'Bachillerato del Estado de Hidalgo',
    'Colegio de Bachilleres del Estado de Hidalgo', 'Colegio de Educación Profesional Técnica del Estado de Hidalgo',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo', 'El Colegio del Estado de Hidalgo',
    'Instituto Hidalguense de Educación', 'Instituto Hidalguense de Educación para Adultos',
    'Instituto Hidalguense de Financiamiento a la Educación Superior', 'Instituto Hidalguense de la Infraestructura Física Educativa',
    'Instituto Hidalguense del Deporte', 'Instituto Tecnológico Superior de Huichapan',
    'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo', 'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo',
    'Radio y Televisión de Hidalgo', 'Universidad Intercultural del Estado de Hidalgo',
    'Universidad Politécnica de Francisco I. Madero', 'Universidad Politécnica de Huejutla',
    'Universidad Politécnica de la Energía', 'Universidad Politécnica de Pachuca',
    'Universidad Politécnica de Tulancingo', 'Universidad Politécnica Metropolitana de Hidalgo',
    'Universidad Tecnológica de la Huasteca Hidalguense', 'Universidad Tecnológica de la Sierra Hidalguense',
    'Universidad Tecnológica de la Zona Metropolitana del Valle de México', 'Universidad Tecnológica de Mineral de la Reforma',
    'Universidad Tecnológica de Tulancingo', 'Universidad Tecnológica de Tula-Tepeji',
    'Universidad Tecnológica del Valle del Mezquital', 'Universidad Tecnológica Minera de Zimapán',
    'Instituto Hidalguense de la Juventud', 'Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo',
    'Sistema de Convencional', 'Sistema de Masivo', 'Comisión Estatal Para el Desarrollo Sostenible de los Pueblos Indígenas',
    'Consejo de Ciencia, Tecnología e Innovación de Hidalgo', 'Consejo Rector de Pachuca Ciudad del Conocimiento y la Cultura',
    'Museo Interactivo para la Niñez y la Juventud "El Rehilete"', 'Secretaría Técnica del Sistema Estatal Anticorrupción',
    'Distrito de Educación, Salud, Ciencia, Tecnología e Innovación', 'Sistema para el Desarrollo Integral de las Familia del Estado de Hidalgo',
    'Universidad Digital del Estado de Hidalgo'
];