// export const regionesConMunicipios = {
//   '01.Tula': [
//     '005 Ajacuba', '010 Atitalaquia', '013 Atotonilco de Tula', '063 Tepeji del Río de Ocampo',
//     '064 Tepetitlán', '065 Tetepango', '067 Tezontepec de Aldama', '070 Tlahuelilpan', '074 Tlaxcoapan', '076 Tula de Allende'
//   ],
//   '02.Tulancingo': [
//     '001 Acatlán', '002 Acaxochitlán', '004 Agua Blanca de Iturbide', '016 Cuautepec de Hinojosa', '027 Huehuetla',
//     '035 Metepec', '053 San Bartolo Tutotepec', '056 Santiago Tulantepec de Lugo Guerrero', '057 Singuilucan', '060 Tenango de Doria', '077 Tulancingo de Bravo'
//   ],
//   '03.Pachuca': ['048 Pachuca de Soto', '052 San Agustin Tlaxiaca', '082 Zapotlán de Juárez'],
//   '04.Huejutla': [
//     '028 Huejutla de Reyes', '011 Atlapexco', '014 Calnali', '025 Huautla', '026 Huazalingo', '032 Jaltocán', '034 Lolotla',
//     '046 San Felipe Orizatlán', '073 Tlanchinol', '078 Xochiatipan', '080 Yahualica'
//   ],
//   '05.Mineral de la Reforma': [
//     '051 Mineral de la Reforma', '022 Epazoyucan', '024 Huasca de Ocampo', '038 Mineral del Chico', '039 Mineral del Monte', '045 Omitlán de Juárez'
//   ],
//   '06.Tizayuca': ['069 Tizayuca', '066 Villa de Tezontepec', '075 Tolcayuca', '083 Zempoala'],
//   '07.Actopan': [
//     '003 Actopan', '009 El Arenal', '023 Francisco I. Madero', '041 Mixquiahuala de Juárez', '050 Progreso de Obregón',
//     '054 San Salvador', '055 Santiago de Anaya'
//   ],
//   '08.Ixmiquilpan': [
//     '030 Ixmiquilpan', '006 Alfajayucan', '015 Cardonal', '019 Chilcuautla', '043 Nicolás Flores', '058 Tasquillo', '084 Zimapán'
//   ],
//   '09.Zacualtipán': [
//     '081 Zacualtipán de Ángeles', '012 Atotonilco el Grande', '020 Eloxochitlán', '033 Juárez Hidalgo',
//     '036 San Agustín Metzquititlán', '037 Metztitlán', '042 Molango de Escamilla', '062 Tepehuacán de Guerrero',
//     '068 Tianguistengo', '071 Tlahuiltepa', '079 Xochicoatlán'
//   ],
//   '10.Apan': [
//     '008 Apan', '007 Almoloya', '021 Emiliano Zapata', '061 Tepeapulco', '072 Tlanalapa'
//   ],
//   '11.Huichapan': [
//     '029 Huichapan', '017 Chapantongo', '044 Nopala de Villagrán', '059 Tecozautla'
//   ],
//   '12.Jacala': [
//     '031 Jacala de Ledezma', '018 Chapulhuacán', '040 La Misión', '047 Pacula', '049 Pisaflores'
//   ]
// };



export const municipiosDeHidalgo = [
    '001 Acatlán', '002 Acaxochitlán', '003 Actopan', '004 Agua Blanca de Iturbide', '005 Ajacuba', '006 Alfajayucan',
    '007 Almoloya', '008 Apan', '009 El Arenal', '010 Atitalaquia', '011 Atlapexco', '012 Atotonilco el Grande',
    '013 Atotonilco de Tula', '014 Calnali', '015 Cardonal', '016 Cuautepec de Hinojosa', '017 Chapantongo',
    '018 Chapulhuacán', '019 Chilcuautla', '020 Eloxochitlán', '021 Emiliano Zapata', '022 Epazoyucan',
    '023 Francisco I. Madero', '024 Huasca de Ocampo', '025 Huautla', '026 Huazalingo', '027 Huehuetla',
    '028 Huejutla de Reyes', '029 Huichapan', '030 Ixmiquilpan', '031 Jacala de Ledezma', '032 Jaltocán',
    '033 Juárez Hidalgo', '034 Lolotla', '035 Metepec', '036 San Agustín Metzquititlán', '037 Metztitlán',
    '038 Mineral del Chico', '039 Mineral del Monte', '040 La Misión', '041 Mixquiahuala de Juárez',
    '042 Molango de Escamilla', '043 Nicolás Flores', '044 Nopala de Villagrán', '045 Omitlán de Juárez',
    '046 San Felipe Orizatlán', '047 Pacula', '048 Pachuca de Soto', '049 Pisaflores', '050 Progreso de Obregón',
    '051 Mineral de la Reforma', '052 San Agustín Tlaxiaca', '053 San Bartolo Tutotepec', '054 San Salvador',
    '055 Santiago de Anaya', '056 Santiago Tulantepec de Lugo Guerrero', '057 Singuilucan', '058 Tasquillo',
    '059 Tecozautla', '060 Tenango de Doria', '061 Tepeapulco', '062 Tepehuacán de Guerrero', '063 Tepeji del Río de Ocampo',
    '064 Tepetitlán', '065 Tetepango', '066 Villa de Tezontepec', '067 Tezontepec de Aldama', '068 Tianguistengo',
    '069 Tizayuca', '070 Tlahuelilpan', '071 Tlahuiltepa', '072 Tlanalapa', '073 Tlanchinol', '074 Tlaxcoapan',
    '075 Tolcayuca', '076 Tula de Allende', '077 Tulancingo de Bravo', '078 Xochiatipan', '079 Xochicoatlán',
    '080 Yahualica', '081 Zacualtipán de Ángeles', '082 Zapotlán de Juárez', '083 Zempoala', '084 Zimapán'
];

export const unidadesResponsables = [
    '01.Poder Legislativo',
    '02.Poder Judicial',
    '03.Instituto Estatal Electoral',
    '04.Comisión de Derechos Humanos del Estado',
    '05.Instituto de Transparencia, Acceso a la Información Pública Gubernamental y Protección de Datos Personales del Estado de Hidalgo',
    '06.Tribunal Electoral del Estado de Hidalgo',
    '10.Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado',
    '11.Secretaría de Gobierno',
    '12.Secretaría de Hacienda',
    '13.Secretaría de Bienestar e Inclusión Social',
    '15.Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible',
    '16.Secretaría de Medio Ambiente y Recursos Naturales',
    '17.Secretaría de Desarrollo Económico',
    '18.Secretaría de Agricultura y Desarrollo Rural',
    '19.Secretaría de Turismo',
    '20.Secretaría de Contraloría',
    '21.Secretaría de Educación Pública',
    '22.Secretaría de Salud',
    '23.Secretaría de Seguridad Pública',
    '24.Secretaría del Trabajo y Previsión Social',
    '26.Secretaría de Movilidad y Transporte',
    '27.Secretaría de Cultura',
    '28.Unidad de Planeación y Prospectiva',
    '29.Oficialía Mayor',
    '30.Procuraduría General de Justicia',
    '40.Organismos Descentralizados',
    '50.Organismos Descentralizados no Sectorizados',
    '60.Municipios'
];

export const dependencias = [
    'Secretaría del Despacho del Gobernador (SDC)', 'Oficialía Mayor (OFM)', 'Unidad de Planeación y Prospectiva (UPI)',
    'Secretaría de Gobierno (COB)', 'Secretaría de Hacienda (HAC)', 'Secretaría de Bienestar e Inclusión Social (SBI)',
    'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible (SIP)', 'Secretaría de Desarrollo Económico (SDE)',
    'Secretaría de Medio Ambiente y Recursos Naturales (SMR)', 'Secretaría de Agricultura y Desarrollo Rural (SAD)',
    'Secretaría de Turismo (TUR)', 'Secretaría de Contraloría (CON)', 'Secretaría de Educación Pública (SEP)',
    'Secretaría de Salud (SLD)', 'Secretaría de Seguridad Pública (SEG)', 'Secretaría del Trabajo y Previsión Social (STP)',
    'Secretaría de Movilidad y Transporte (SMT)', 'Secretaría de Cultura (CUL)', 'Procuraduría de General de Justicia (PGJ)'
];

export const organismos = [
    'Centro de Justicia para Mujeres del Estado de Hidalgo (CJM)', 'Ciudad de las Mujeres (CMU)', 'Instituto Hidalguense de las Mujeres (IMU)',
    'Instituto Hidalguense para el Desarrollo Municipal (IND)', 'Instituto Catastral del Estado de Hidalgo (ICA)',
    'Instituto para Devolver al Pueblo lo Robado (IPR)', 'Centro Estatal de Maquinaria para el Desarrollo (CMD)',
    'Comisión de Agua y Alcantarillado de Sistemas del Valle del Mezquital (CAV)', 'Comisión de Agua y Alcantarillado de Sistemas Intermunicipales (CAI)',
    'Comisión Estatal de Agua y Alcantarillado (CEA)', 'Comisión Estatal de Vivienda (CEV)', 'Policía Industrial Bancaria del Estado de Hidalgo (PIB)',
    'Consejo Estatal para la Cultura y las Artes de Hidalgo (CCA)', 'Escuela de Música del Estado de Hidalgo (EMH)',
    'Servicios de Salud de Hidalgo (SSH)', 'Agencia de Desarrollo Valle de Plata (AVP)', 'Agencia Estatal de Energía (AEE)',
    'Corporación de Fomento de Infraestructura Industrial (FII)', 'Corporación Internacional Hidalgo (CIH)',
    'Instituto Hidalguense de Competitividad (IHC)', 'Comisión Estatal de Biodiversidad de Hidalgo (COE)',
    'Centro de Conciliación Laboral del Estado de Hidalgo (CLH)', 'Instituto de Capacitación para el Trabajo del Estado de Hidalgo (CTH)',
    'Operadora de Eventos del Estado de Hidalgo (OEH)', 'Bachillerato del Estado de Hidalgo (BEH)',
    'Colegio de Bachilleres del Estado de Hidalgo (CBH)', 'Colegio de Educación Profesional Técnica del Estado de Hidalgo (EPT)',
    'Colegio de Estudios Científicos y del Estado de Hidalgo (ECT)', 'El Colegio del Estado de Hidalgo (CEH)',
    'Instituto Hidalguense de Educación (IHE)', 'Instituto Hidalguense de Educación para Adultos (IHEA)',
    'Instituto Hidalguense de Financiamiento a la Educación Superior (IHFES)', 'Instituto Hidalguense de Ia Infraestructura Física Educativa (IFE)',
    'Instituto Hidalguense del Deporte (IHD)', 'Instituto Tecnológico Superior de Huichapan (ITESHU)',
    'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo (ITSOEH)', 'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo (ITESA)',
    'Radio y Televisión de Hidalgo (RTH)', 'Universidad Intercultural del Estado de Hidalgo (UICEH)',
    'Universidad Politécnica de Francisco l. Madero (UPFIM)', 'Universidad Politécnica de Huejutla (UPHUE)',
    'Universidad Politécnica de la Energía (UPE)', 'Universidad Politécnica de Pachuca (UPP)',
    'Universidad Politécnica de Tulancingo (UPT)', 'Universidad Politécnica Metropolitana de Hidalgo (UPMH)',
    'Universidad Tecnológica de la Huasteca Hidalguense (UTHH)', 'Universidad Tecnológica de la Sierra Hidalguense (UTSH)',
    'Universidad Tecnológica de la Zona Metropolitana del Valle de México (UTVAM)', 'Universidad Tecnológica de Mineral de la Reforma (UTMIR)',
    'Universidad Tecnológica de Tulancingo (UTT)', 'Universidad Tecnológica de Tula-Tepejí (UTTT)',
    'Universidad Tecnológica del Valle del Mezquital (UTVM)', 'Universidad Tecnológica Minera de Zimapán (UTMZ)',
    'Instituto Hidalguense de la Juventud (IHJ)', 'Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo (IAA)',
    'Sistema de Convencional (STC)', 'Sistema de Masivo (STM)', 'Comisión Estatal para el Desarrollo de los Pueblos Indígenas en el Estado de Hidalgo (CPI)',
    'Consejo de Ciencia, Tecnología e Innovación de Hidalgo (CCT)', 'Consejo Rector de Pachuca Ciudad del Conocimiento y la Cultura (CCC)',
    'Museo Interactivo para la Niñez y Juventud Hidalguense El Rehilete (MIR)', 'Secretaría Técnica del Sistema Estatal Anticorrupción de Hidalgo (STSEA)',
    'Distrito de Educación, Salud, Ciencia, Tecnología e Innovación (DESTI)', 'Sistema para el Desarrollo Integral de la Familia Hidalgo (DIF)',
    'Universidad Digital del Estado de Hidalgo (UDH)'
];


export const unidadPresupuestalPorUnidadResponsable = {
    '01.Poder Legislativo': [
        '01.Presidencia de la Junta de Gobierno',
        '02.Asamblea del Congreso',
        '03.Secretaría de Servicios Legislativos',
        '04.Auditoría Superior del Estado de Hidalgo',
        '05.Dirección General de Servicios Administrativos',
        '06.Coordinación de Asesoría',
        '07.Instituto de Estudios Legislativos',
        '08.Instituto para el Desarrollo y Fortalecimiento Municipal',
        '09.Dirección de Comunicación Social',
        '10.Comisión para la revisión integral del marco legal del Estado de Hidalgo'
    ],
    '02.Poder Judicial': [
        '01.Tribunal Superior de Justicia',
        '03.Tribunal de Justicia Administrativa'
    ],
    '03.Instituto Estatal Electoral': [
        '01.Instituto Estatal Electoral'
    ],
    '04.Comisión de Derechos Humanos del Estado': [
        '01.Comisión de Derechos Humanos del Estado'
    ],
    '05.Instituto de Transparencia, Acceso a la Información Pública Gubernamental y Protección de Datos Personales del Estado de Hidalgo': [
        '01.Instituto de Transparencia, Acceso a la Información Pública Gubernamental y Protección de Datos Personales del Estado de Hidalgo'
    ],
    '06.Tribunal Electoral del Estado de Hidalgo': [
        '01.Tribunal Electoral del Estado'
    ],
    '10.Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado': [
        '01.Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado',
        '02.Dirección General de Relaciones Públicas',
        '15.Secretaría Técnica del Despacho del Gobernador',
        '16.Dirección General de Estudios Legislativos',
        '17.Coordinación de Agenda y Audiencia Pública',
        '18.Dirección General de Giras',
        '19.Dirección General de Atención al Pueblo',
        '20.Dirección General de Desarrollo Institucional',
        '21.Coordinación de Seguimiento',
        '22.Coordinación de Gestión y Vinculación de Proyectos Especiales',
        '23.Coordinación de Operación Institucional'
    ],
    '11.Secretaría de Gobierno': [
        '01.Secretaría de Gobierno',
        '02.Subsecretaría de Gobernación',
        '04.Dirección General de Investigaciones Políticas y Sociales',
        '09.Dirección General de Asuntos Agrarios',
        '10.Subsecretaría de Gobierno en la Huasteca Hidalguense',
        '12.Subsecretaría de Gobierno en el Valle del Mezquital',
        '13.Subsecretaría de Desarrollo Político',
        '14.Dirección General de Desarrollo Político',
        '15.Coordinación General Jurídica',
        '16.Dirección General Jurídica',
        '17.Subsecretaría de Protección Civil y Gestión de Riesgos',
        '18.Dirección General de Protección Civil y Gestión de Riesgos',
        '19.Central Estatal de Información, Investigación e Inteligencia',
        '24.Consejo Estatal de Población',
        '27.Instituto de la Defensoría Pública del Estado de Hidalgo',
        '28.Dirección General del Mando Coordinado',
        '29.Dirección General del Instituto de la Función Registral',
        '30.Secretaría Ejecutiva del Sistema Estatal de Protección Integral de los derechos de Niñas, Niños y Adolescentes del Estado de Hidalgo',
        '31.Secretariado Ejecutivo del Consejo Estatal de Seguridad Pública',
        '33.Dirección General de Asuntos Religiosos',
        '34.Dirección General de Unidades de Servicios Estatales',
        '35.Coordinación General de Comunicación Gubernamental',
        '36.Dirección General de Derechos Humanos',
        '37.Dirección General del Registro del Estado Familiar',
        '38.Dirección General de Archivo General de Notarías',
        '39.Comisión de Búsqueda de Personas del Estado de Hidalgo',
        '40.Dirección General Editorial'
    ],
    '12.Secretaría de Hacienda': [
        '01.Secretaría de Hacienda',
        '02.Coordinación de Planeación Financiera',
        '03.Procuraduría Fiscal del Estado de Hidalgo',
        '05.Unidad Técnica de Evaluación del Desempeño',
        '08.Subsecretaría de Egresos',
        '09.Dirección General de Contabilidad Gubernamental',
        '10.Dirección General de Tesorería',
        '11.Dirección General de Normatividad Contable Presupuestal',
        '13.Dirección General de Atención y Seguimiento a Auditorías',
        '14.Subsecretaría de Ingresos',
        '15.Dirección General de Auditoría Fiscal',
        '16.Dirección General de Recaudación',
        '23.Coordinación de Tecnologías de la Información',
        '25.Dirección General de Atención al Contribuyente',
        '26.Coordinación del Gasto de Inversión',
        '27.Subsecretaría de Programación y Presupuesto del Gasto de Inversión',
        '28.Dirección General de Programación',
        '29.Dirección General de Validación Técnica de Estudios y Proyectos',
        '30.Dirección General de Monitoreo y Seguimiento al Recurso Público',
        '31.Coordinación de Representación Institucional',
        '32.Unidad de Inteligencia Patrimonial y Económica',
        '33.Dirección General de Administración'
    ],
    '13.Secretaría de Bienestar e Inclusión Social': [
        '01.Secretaría de Bienestar e Inclusión Social',
        '04.Dirección General de Fomento Artesanal',
        '05.Subsecretaría de Inclusión y Desarrollo',
        '06.Dirección General de Operación y Logística de Programas',
        '07.Dirección General de Atención al Migrante',
        '08.Dirección General de Asistencia, Atención y Protección',
        '12.Dirección General de Prospectiva, Planeación y Evaluación de los Programas Sociales',
        '13.Subsecretaría de Participación Social y Fomento Artesanal',
        '14.Dirección General de Inclusión para las Personas con Discapacidad',
        '15.Subsecretaría de Desarrollo Social y Humano'
    ],
    '15.Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': [
        '01.Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible',
        '02.Subsecretaría de Infraestructura Pública',
        '03.Dirección General de Obras Públicas e Infraestructura',
        '04.Dirección General de Infraestructura y Vías de Comunicación',
        '05.Dirección General de Conservación de Carreteras Estatales',
        '06.Subsecretaría de Desarrollo Urbano Sostenible',
        '07.Dirección General de Imagen y Desarrollo Urbano Sostenible',
        '08.Subsecretaría de Gestión de Proyectos',
        '09.Dirección General de Estudios y Proyectos',
        '10.Dirección General de Supervisión Estratégica y Evaluación',
        '11.Dirección General de Tecnologías de Información y Mejora Continua',
        '12.Dirección General de Asuntos Jurídicos',
        '13.Dirección General de Administración',
        '14.Dirección General de Atención y Vinculación Institucional'
    ],
    '16.Secretaría de Medio Ambiente y Recursos Naturales': [
        '01.Secretaría de Medio Ambiente y Recursos Naturales',
        '02.Subsecretaría de Política Ambiental',
        '03.Dirección General de Ordenamiento Ecológico Territorial',
        '04.Dirección General de Recursos Naturales',
        '06.Dirección General de Gestión de Calidad del Aire',
        '07.Consejo de Administración del Parque Nacional "El Chico"',
        '09.Procuraduría Estatal de Protección al Ambiente',
        '10.Dirección General de Normatividad Ambiental',
        '11.Dirección General de Cuencas y Planeación Hídrica',
        '12.Subsecretaría de Sustentabilidad y Cambio Climático',
        '13.Dirección General de Cambio Climático'
    ],
    '17.Secretaría de Desarrollo Económico': [
        '01.Secretaría de Desarrollo Económico',
        '02.Subsecretaría de Inversiones y Economía Sectorial',
        '03.Dirección General de Economía Sectorial',
        '04.Dirección General de Inversiones',
        '05.Subsecretaría de Fomento Económico',
        '06.Dirección General de Fomento al Empleo',
        '07.Dirección General de Fomento Económico'
    ],
    '18.Secretaría de Agricultura y Desarrollo Rural': [
        '01.Secretaría de Agricultura y Desarrollo Rural',
        '02.Subsecretaría de Desarrollo Agropecuario',
        '03.Dirección General de Agricultura',
        '04.Dirección General de Ganadería',
        '07.Dirección General de Desarrollo Rural',
        '08.Dirección General de Silvicultura, Fruticultura, Acuacultura y del Maguey',
        '09.Dirección General de Infraestructura y Maquinaria',
        '10.Subsecretaría de Agronegocios',
        '11.Dirección General de Comercialización y Mercadotecnia',
        '12.Subsecretaría de Planeación y Evaluación Sectorial',
        '13.Dirección General de Evaluación y Programas Estratégicos',
        '14.Dirección General de Fomento al Crédito',
        '15.Dirección General de Fomento Lechero',
        '16.Dirección General de Desarrollo de la Cafeticultura'
    ],
    '19.Secretaría de Turismo': [
        '01.Secretaría de Turismo',
        '02.Dirección General de Productos Turísticos y Pueblos Mágicos',
        '04.Dirección General de Promoción y Mercadotecnia',
        '05.Dirección General de Formación y Competitividad Turística',
        '06.Dirección General de Programas Turísticos y Alianzas Estratégicas',
        '07.Dirección de Planeación y Evaluación',
        '08.Subsecretaría de Turismo',
        '09.Dirección de Innovación, Desarrollo de Productos Turísticos e Infraestructura'
    ],
    '20.Secretaría de Contraloría': [
        '01.Secretaría de Contraloría',
        '02.Dirección General de Órganos de Control y Vigilancia',
        '03.Dirección General de Inspección y Vigilancia de Obras y Acciones',
        '08.Dirección General de Normatividad',
        '10.Dirección General de Responsabilidades Administrativas',
        '11.Dirección General de Vinculación',
        '12.Dirección General de Auditoría Gubernamental'
    ],
    '21.Secretaría de Educación Pública': [
        '01.Secretaría de Educación Pública',
        '02.Subsecretaría de Administración y Finanzas',
        '03.Subsecretaría de Educación Básica',
        '04.Subsecretaría de Educación Media Superior y Superior',
        '05.Subsecretaría de Planeación y Evaluación',
        '06.Centro Estatal de Lenguas y Culturas Indígenas'
    ],
    '22.Secretaría de Salud': [
        '01.Secretaría de Salud',
        '02.Subsecretaría de Salud Pública',
        '03.Subsecretaría de Servicios de Salud',
        '04.Subsecretaría de Administración, Finanzas y Planeación',
        '07.Comisión de Arbitraje Médico del Estado de Hidalgo',
        '14.Comisión para la Protección contra Riesgos Sanitarios del Estado de Hidalgo',
        '17.Dirección General de Proyectos Estratégicos de Salud',
        '20.Centro Estatal de Trasplantes de Órganos, Tejidos y Células de Humanos para el Estado de Hidalgo'
    ],
    '23.Secretaría de Seguridad Pública': [
        '01.Secretaría de Seguridad Pública',
        '02.Subsecretaría de Prevención y Reinserción Social',
        '03.Dirección General de Prevención y Reinserción Social',
        '04.Subsecretaría de C5i',
        '05.Dirección General de Servicios Aéreos',
        '06.Subsecretaría de Prevención y Coordinación Institucional',
        '07.Dirección General del Centro Estatal de Prevención Social de la Violencia y la Delincuencia',
        '08.Dirección General de Asuntos Jurídicos y Derechos Humanos',
        '10.Subsecretaría de Operación Policial',
        '15.Instituto de Formación Profesional',
        '16.Centro Estatal de Evaluación y Control de Confianza',
        '17.Unidad de Medidas Cautelares',
        '18.Dirección General de Ayudantía Personal',
        '19.Dirección General de Supervisión e Inspección Interna'
    ],
    '24.Secretaría del Trabajo y Previsión Social': [
        '01.Secretaría del Trabajo y Previsión Social',
        '02.Dirección General del Trabajo y Previsión Social',
        '03.Dirección General del Servicio Nacional de Empleo',
        '04.Junta Local de Conciliación y Arbitraje',
        '05.Tribunal de Arbitraje',
        '06.Procuraduría Estatal de la Defensa del Trabajo'
    ],
    '26.Secretaría de Movilidad y Transporte': [
        '01.Secretaría de Movilidad y Transporte',
        '02.Subsecretaría de Movilidad y Transporte',
        '03.Dirección General de Normatividad',
        '04.Dirección General de Movilidad Sustentable'
    ],
    '27.Secretaría de Cultura': [
        '01.Secretaría de Cultura',
        '02.Dirección General de Diversidad Cultural y Fomento a la Lectura, Escritura y Oralidad',
        '04.Dirección General de Cultura Digital',
        '06.Dirección General de Vinculación, Programación y Difusión Cultural',
        '07.Subsecretaría de Desarrollo Cultural',
        '08.Dirección General de Cultura Originaria, Popular y Urbana',
        '10.Dirección General de Patrimonio Cultural'
    ],
    '28.Unidad de Planeación y Prospectiva': [
        '01.Unidad de Planeación y Prospectiva',
        '03.Coordinación General de Normatividad y Entidades Paraestatales',
        '04.Dirección General de Consulta y Normatividad',
        '05.Dirección General de Control y Seguimiento a Entidades Paraestatales',
        '07.Coordinación General de Planeación y Proyectos',
        '08.Dirección General de Análisis Geográfico y Mejora a las Políticas Públicas',
        '09.Dirección General de Planeación y Participación Ciudadana',
        '10.Dirección General de Desarrollo Regional y Metropolitano',
        '11.Coordinación General de Evaluación y Políticas Públicas',
        '12.Dirección General de Evaluación',
        '14.Dirección General de Monitoreo',
        '15.Dirección General de Percepción e Impacto Ciudadano',
        '16.Dirección General de Proyectos, Estudios y Prospectiva',
        '17.Comisión Estatal de Mejora Regulatoria'
    ],
    '29.Oficialía Mayor': [
        '01.Oficialía Mayor',
        '02.Dirección General de Compras Públicas',
        '03.Dirección General de Patrimonio Inmobiliario',
        '04.Dirección General de Recursos Materiales y Servicios',
        '05.Dirección General de Recursos Humanos',
        '07.Archivo General del Estado de Hidalgo',
        '08.Dirección General de Innovación Gubernamental',
        '09.Coordinación General de la Oficialía Mayor'
    ],
    '30.Procuraduría General de Justicia': [
        '01.Procuraduría General de Justicia',
        '02.Subprocuraduría Oriente',
        '04.Dirección General del Sistema Mixto',
        '05.Fiscalía Especializada en Delitos Electorales',
        '06.Subprocuraduría de Delitos de Género, Desaparición de Personas e Impacto Social',
        '09.Visitaduría General',
        '12.Unidad Especializada en el Combate al Secuestro',
        '13.Oficialía Mayor',
        '15.Subprocuraduría Poniente',
        '23.Fiscalía Especializada en Delitos de Corrupción',
        '25.Subprocuraduría Jurídica y de Derechos Humanos',
        '26.Unidad de Recuperación de Vehículos',
        '27.Agencia de investigación Criminal',
        '28.Centro de Justicia Restaurativa',
        '29.Órgano Interno de Control'
    ],
    '40.Organismos Descentralizados': [
        '01.Radio y Televisión de Hidalgo',
        '03.Instituto Hidalguense para el Desarrollo Municipal',
        '05.Instituto Catastral del Estado de Hidalgo',
        '07.Instituto Hidalguense de las Mujeres',
        '08.Instituto Hidalguense de la Juventud',
        '09.Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo',
        '14.Centro Estatal de Maquinaria para el Desarrollo',
        '16.Comisión Estatal de Vivienda',
        '18.Comisión Estatal del Agua y Alcantarillado',
        '19.Comisión de Agua y Alcantarillado de Sistemas Intermunicipales',
        '20.Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital',
        '21.Instituto de Vivienda, Desarrollo Urbano y Asentamientos Humanos',
        '22.Sistema de Autopistas, Servicios Conexos y Auxiliares del Estado de Hidalgo',
        '23.Corporación Internacional Hidalgo',
        '24.Corporación de Fomento de Infraestructura Industrial',
        '26.Operadora de Eventos del Estado de Hidalgo',
        '27.Instituto Hidalguense de Competitividad Empresarial',
        '28.Agencia de Desarrollo Valle de Plata',
        '34.Consejo Estatal para la Cultura y las Artes de Hidalgo',
        '36.Instituto Hidalguense de Educación',
        '38.Instituto Hidalguense de Educación para Adultos',
        '39.Universidad Politécnica de Tulancingo',
        '40.Universidad Politécnica de Pachuca',
        '41.Universidad Politécnica de Francisco I. Madero',
        '42.Universidad Politécnica de Huejutla',
        '43.Universidad Politécnica Metropolitana de Hidalgo',
        '44.Universidad Tecnológica de Tula–Tepeji',
        '45.Universidad Tecnológica de Tulancingo',
        '46.Universidad Tecnológica de la Huasteca Hidalguense',
        '47.Universidad Tecnológica del Valle del Mezquital',
        '48.Universidad Tecnológica de la Sierra Hidalguense',
        '49.Universidad Tecnológica de la Zona Metropolitana del Valle de México',
        '50.Instituto Tecnológico Superior de Huichapan',
        '51.Instituto Tecnológico Superior del Occidente del Estado de Hidalgo',
        '52.Instituto Tecnológico Superior del Oriente del Estado de Hidalgo',
        '53.Universidad Intercultural del Estado de Hidalgo',
        '54.Colegio de Bachilleres del Estado de Hidalgo',
        '55.Bachillerato del Estado de Hidalgo',
        '56.Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo',
        '57.Colegio de Educación Profesional Técnica del Estado de Hidalgo',
        '58.El Colegio del Estado de Hidalgo',
        '59.Escuela de Música del Estado de Hidalgo',
        '60.Instituto Hidalguense de Financiamiento a la Educación Superior',
        '61.Instituto Hidalguense del Deporte',
        '63.Instituto Hidalguense de la Infraestructura Física Educativa',
        '65.Servicios de Salud de Hidalgo',
        '68.Instituto de Capacitación para el Trabajo del Estado de Hidalgo',
        '69.Policía Industrial Bancaria del Estado de Hidalgo',
        '70.Centro de Justicia para Mujeres del Estado de Hidalgo',
        '71.Sistema de Transporte Convencional de Hidalgo',
        '72.Sistema Integrado de Transporte Masivo de Hidalgo',
        '73.Universidad Tecnológica Minera de Zimapán',
        '76.Universidad Tecnológica de Mineral de la Reforma',
        '77.Universidad Politécnica de la Energía',
        '80.Ciudad de las Mujeres',
        '81.Agencia Estatal de Energía de Hidalgo',
        '82.Centro de Conciliación Laboral del Estado de Hidalgo',
        '83.Comisión Estatal de Biodiversidad de Hidalgo',
        '84.Universidad Digital del Estado de Hidalgo',
        '85.Comisión Ejecutiva de Atención a Víctimas del Estado de Hidalgo',
        '86.Instituto Hidalguense para Devolver al Pueblo lo Robado'
    ],
    '50.Organismos Descentralizados no Sectorizados': [
        '01.Secretaría Técnica del Sistema Estatal Anticorrupción de Hidalgo',
        '02.Sistema para el Desarrollo Integral de la Familia del Estado de Hidalgo',
        '03.Comisión Estatal para el Desarrollo Sostenible de los Pueblos Indígenas (CEDSPI)',
        '04.Consejo de Ciencia, Tecnología e Innovación de Hidalgo (CITNOVA)',
        '05.Universidad Autónoma del Estado de Hidalgo',
        '06.Museo Interactivo para la Niñez y la Juventud Hidalguense “El Rehilete”',
        '08.Consejo Ejecutivo del Complejo Científico y Tecnológico Sincrotrón en el Estado de Hidalgo',
        '09.Coordinación General del Distrito de Educación, Salud, Ciencia, Tecnología e Innovación'
    ],
    '60.Municipios': [
        '01.Acatlán',
        '02.Acaxochitlán',
        '03.Actopan',
        '04.Agua Blanca de Iturbide',
        '05.Ajacuba',
        '06.Alfajayucan',
        '07.Almoloya',
        '08.Apan',
        '09.El Arenal',
        '10.Atitalaquia',
        '11.Atlapexco',
        '12.Atotonilco el Grande',
        '13.Atotonilco de Tula',
        '14.Calnali',
        '15.Cardonal',
        '16.Cuautepec de Hinojosa',
        '17.Chapantongo',
        '18.Chapulhuacán',
        '19.Chilcuautla',
        '20.Eloxochitlán',
        '21.Emiliano Zapata',
        '22.Epazoyucan',
        '23.Francisco I. Madero',
        '24.Huasca de Ocampo',
        '25.Huautla',
        '26.Huazalingo',
        '27.Huehuetla',
        '28.Huejutla de Reyes',
        '29.Huichapan',
        '30.Ixmiquilpan',
        '31.Jacala de Ledezma',
        '32.Jaltocán',
        '33.Juárez Hidalgo',
        '34.Lolotla',
        '35.Metepec',
        '36.San Agustín Metzquititlán',
        '37.Metztitlán',
        '38.Mineral del Chico',
        '39.Mineral del Monte',
        '40.La Misión',
        '41.Mixquiahuala de Juárez',
        '42.Molango de Escamilla',
        '43.Nicolás Flores',
        '44.Nopala de Villagrán',
        '45.Omitlán de Juárez',
        '46.San Felipe Orizatlán',
        '47.Pacula',
        '48.Pachuca de Soto',
        '49.Pisaflores',
        '50.Progreso de Obregón',
        '51.Mineral de la Reforma',
        '52.San Agustín Tlaxiaca',
        '53.San Bartolo Tutotepec',
        '54.San Salvador',
        '55.Santiago de Anaya',
        '56.Santiago Tulantepec de Lugo Guerrero',
        '57.Singuilucan',
        '58.Tasquillo',
        '59.Tecozautla',
        '60.Tenango de Doria',
        '61.Tepeapulco',
        '62.Tepehuacán de Guerrero',
        '63.Tepeji del Río de Ocampo',
        '64.Tepetitlán',
        '65.Tetepango',
        '66.Villa de Tezontepec',
        '67.Tezontepec de Aldama',
        '68.Tianguistengo',
        '69.Tizayuca',
        '70.Tlahuelilpan',
        '71.Tlahuiltepa',
        '72.Tlanalapa',
        '73.Tlanchinol',
        '74.Tlaxcoapan',
        '75.Tolcayuca',
        '76.Tula de Allende',
        '77.Tulancingo de Bravo',
        '78.Xochiatipan',
        '79.Xochicoatlán',
        '80.Yahualica',
        '81.Zacualtipán de Ángeles',
        '82.Zapotlán de Juárez',
        '83.Zempoala',
        '84.Zimapán'
    ]
};


export const ramoPresupuestalOptions = [
    '1.Legislativo',
    '2.Judicial',
    '3.Electoral',
    '4.Derechos Humanos',
    '5.Acceso a la Información Pública Gubernamental',
    '6.Justicia Electoral',
    '7.Despacho del Poder Ejecutivo',
    '8.Gobierno',
    '9.Hacienda Pública',
    '10.Bienestar e Inclusión Social',
    '11.Infraestructura Pública y Desarrollo Urbano Sostenible',
    '12.Medio Ambiente y Recursos Naturales',
    '13.Desarrollo Económico',
    '14.Agricultura y Desarrollo Rural',
    '15.Turismo',
    '16.Contraloría',
    '17.Educación Pública',
    '18.Salud',
    '19.Seguridad Pública',
    '20.Trabajo y Previsión Social',
    '22.Movilidad y Transporte',
    '23.Cultura',
    '24.Planeación y Prospectiva',
    '25.Administración',
    '26.Justicia',
    '27.Transferencias',
    '28.Participaciones a Municipios',
    '29.Contingencias',
    '30.Provisiones Salariales',
    '31.Deuda Pública',
    '32.Adeudos de Ejercicios Fiscales Anteriores',
    '33.Aportaciones a Municipios',
    '34.Erogaciones para las Operaciones y Programas de Saneamiento Financiero',
    '35.Erogaciones para los Programas de Apoyo a Ahorradores y Deudores de la Banca',
    '36.Inversión en Municipios',
];